model:
  model_type: "cnn"
  repr_type: "mfcc"
  mfcc_deltas: True
  conv_layers:
    - type: "conv"
      kernel_count: 32
      kernel_size: 3
      stride: 1
      padding: 0
      batch_norm: True
    - type: "pool"
      kernel_size: 2
      stride: 2
      padding: 0
    - type: "conv"
      kernel_count: 64
      kernel_size: 3
      stride: 1
      padding: 0
      batch_norm: True
    - type: "pool"
      kernel_size: 2
      stride: 2
      padding: 0
    - type: "conv"
      kernel_count: 96
      kernel_size: 3
      stride: 1
      padding: 0
      batch_norm: True
    - type: "pool"
      kernel_size: 2
      stride: 2
      padding: 0
  pool_type: "max"
  fc_layers:
    - 512
    - 128
  dropout: 0.5
  num_classes: 50

run:
  seed: 42
  folds_train:
    - 1
    - 2
    - 3
  folds_val:
    - 4
  batch_size: 32
  num_epochs: 50
  optimizer: "SGD"
  lr: 0.001
  momentum: 0.9
  weight_decay: 0.001
