model:
  model_type: "lstm"
  repr_type: "mel"
  mfcc_deltas: False
  hidden_size: 256
  num_layers: 2
  dropout: 0.3
  bidirectional: true
  pooling: "mean_max"
  fc_layers: [256]
  num_classes: 50

run:
  seed: 42
  folds_train:
    - 1
    - 2
    - 3
    - 4
  folds_val:
    - 5
  batch_size: 32
  num_epochs: 100
  optimizer: "ADAMW"
  lr: 0.001
  momentum: null
  weight_decay: 0.01

  scheduler: "cosine"
  factor: 0.1
  patience: 10
  min_lr: 0.000001
  step_size: null

  warmup_lr: true
  warmup_epochs: 5
  warmup_lr_val: 0.0001

  augment: true
  freq_masks: 2        
  freq_mask_width: 16
  time_masks: 2
  time_mask_width: 40