model:
  model_type: "lstm"
  repr_type: "mfcc"
  mfcc_deltas: True
  hidden_size: 128
  num_layers: 2
  dropout: 0.3
  fc_layers:
    - 128
  num_classes: 50

run:
  seed: 42
  folds_train:
    - 1
    - 2
    - 3
  folds_val:
    - 4
  batch_size: 32
  num_epochs: 2
  optimizer: "SGD"
  lr: 0.001
  momentum: null
  weight_decay: 0.0

  scheduler: "plateau"
  factor: 0.1
  patience: 5
  min_lr: 0.000001
  step_size: null

  augment: true
  freq_masks: 2
  freq_mask_width: 10
  time_masks: 2
  time_mask_width: 25
